### ISSUE TITLE
Configuration is missing.

### ISSUE THREAD

**Issue by rahimnagori** [greencatsoft/ckeditor-spacingsliders#5]
hey @mysticfall , I cannot edit the core plugin.js. Could you please create a functionality to reconfigure this plugin?

**Comment by rahimnagori** [comment]
hey @Sensetivity , can you please help me with this ? or can you please merge a pending request by me?

**Comment by mysticfall** [comment]
Is it a different issue from #1?

**Comment by rahimnagori** [comment]
> Is it a different issue from #3?

No #3, is regarding the same issue.

**Comment by mysticfall** [comment]
Ok, then let's track this with #3.
